language: python

python: '3.6'
sudo: false

# We don't care about Travis' python versions, we install conda anyway
env:
  global:
    - AWS_DEFAULT_REGION=ap-northeast-1
    - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH

install:
  - pip install awscli
  - pip install boto3

  # install libs from the requirements of each single lambda
  - for i in src/*/; do pip install -r $i"requirements.txt"; done

script:
  # run tests
  - py.test -vv -r sxX

before_deploy:
  - echo "before deploy"
  # - mkdir -p dist
  # create zip for each lambda folder in src
  # - for i in src/*/; do .travis/build_lambda.sh "$i"; done

deploy:
  - provider: script
    script: for i in src/*/; do .travis/deploy_lambda.sh "$i"; done
    skip_cleanup: true
    on:
      branch: master

notifications:
  email: true
